const { Router } = require('express')
const News = require('./news/news')
const OneNews = require('./news/news_one')
const Announcements = require('./announcements/announcements')
const OneAnnouncements = require('./announcements/announcements_one')
const Login = require('./login/login')
const SubCategories = require('./sub_categories/sub_category')
const Uploader = require('./uploader/uploader')
const router = new Router()
router
    .get('/news/all', News.GET)
    .get('/news/one/:id', OneNews.GET)
    .get('/announcements/all', Announcements.GET)
    .post('/announcements/add', Announcements.POST)
    .delete('/announcements/delete', Announcements.DELETE)
    .get('/announcements/one/:id', OneAnnouncements.GET)
    .post('/announcements/edit', Announcements.EDIT)
    .post('/login', Login.POST)
    .post('/news/add', News.POST)
    .delete('/news/delete', News.DELETE)
    .post('/news/edit', News.UPDATE)
    .get('/sub_categories/all', SubCategories.GET_ALL)
    .get('/sub_categories/all_sc', SubCategories.GET_ALL_SC)
    .get('/sub_categories/consists_sc', SubCategories.GET_CONSISTS_SC)
    .get('/sub_categories/sub_student_sc', SubCategories.GET_SUB_STUDENT_SC)
    .get('/sub_categories/student_sc', SubCategories.GET_STUDENT_SC)
    .get('/sub_categories/working_sc', SubCategories.GET_WORKING_SC)
    .get('/sub_categories/contacts_sc', SubCategories.GET_CONTACTS_SC)
    .get('/sub_categories/interactive_sc', SubCategories.GET_INTERACTIVE_SC)
    .get('/sub_categories/corruption_sc', SubCategories.GET_CORRUPTION_SC)
    .get('/sub_categories/get/:id', SubCategories.GET_ONE)
    .post('/sub_categories/add', SubCategories.ADD_NEW)
    .delete('/sub_categories/delete', SubCategories.DELETE)
    .post('/sub_categories/edit', SubCategories.EDIT)
    .get('/sub_categories/find/:question', SubCategories.FILTER_SC)
    .get('/media/all', Uploader.GET_ALL_MEDIA)
    .delete('/media/delete', Uploader.DELETE)

    


module.exports = router